version: '3'

services:
  postgres:
    image: postgres
    container_name: sukkiri-sql
    build:
      context: .
    tty: true
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
